### ISSUE TITLE
github action to build for windows

### ISSUE THREAD

**Issue by gjcarrette** [jgaa/shinysocks#7]
Currently I am evaluating proxy solutions to run from a windows command line by a non-privileged user and provide a proxy for programs running under Windows Subsystem for Linux (WSL) or as guests under HYPER-V. These programs tend to only have reliable access to Ethernet adapter vEthernet local between guests and host only. I will be attempting a windows build using https://code.visualstudio.com/docs/languages/cpp or https://visualstudio.microsoft.com/vs/community/

If that works out then I will be submitting a pull request to use a github action workflow to build the executable using a https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners with the EXE as an artifact.

There are quiet a few developers using laptops with Window and also WSL a HYPER-V using Ubuntu and other distributions, and depending on what the corporate IT team has installed on the host Windows environment in terms of firewall configurations and commercial VPN solutions, the connectivity issues for WSL and HYPER-V guests can be as tricky. So I anticipate a lot of demand for a simple, clean solution.

**Comment by jgaa** [comment]
Shinysocks is now built and tested for Linux, Windows and MacOS using Github Actions .
