### ISSUE TITLE
Build failure: cmake/external-projects.cmake missing

### ISSUE THREAD

**Issue by s-maguire** [jgaa/shinysocks#8]
The required file cmake/external-projects.cmake is not in the repo, the logging header which it presumably provides is nowhere to be found either and there are no directions for adding it.

**Comment by jgaa** [comment]
Sorry about that. 
I have added the missing files to a branch: [fix-cmake](https://github.com/jgaa/shinysocks/tree/fix-cmake)

I need to test it with Windows and MacOS before I mere it to (the broken) master branch.
